### ISSUE TITLE
can't add action to Approval process

### ISSUE THREAD

**Issue by lwasowsk** [developerforce/WearablePack-AndroidWear#4]
I noticed that the approval process in Salesforce doesn't update the status on an approved Quote to "Approved"... so I tried adding a field update both as an approver action and as a final approver action, but that throws an error 
10:48:01.131 (131198950)|FATAL_ERROR|System.DmlException: Process failed. First exception on row 0; first error: ALREADY_IN_PROCESS, Cannot submit object already in process.: []

Trigger.CGDemo2015.QuoteApproval: line 20, column 1
10:48:01.131 (131211270)|FATAL_ERROR|System.DmlException: Process failed. First exception on row 0; first error: ALREADY_IN_PROCESS, Cannot submit object already in process.: []

Any ideas?

**Comment by jamesward** [comment]
I've fixed this in the metadata in this repo.  I tested this by adding a `Field Update` to the `Final Approval Actions` on `QuoteDiscountApproval `.  Let me know if that helps.

**Comment by lwasowsk** [comment]
Hi James,
I tested out this (requires manually creating a Field Update called "Status_Update"), but am still getting the same error.  Were you able to have it execute the Field Update in your environment?

**Comment by jamesward** [comment]
Yeah, this worked in my environment.  Maybe you have another trigger on `Quote` already?  See: https://salesforce.stackexchange.com/questions/19207/getting-error-while-submitting-approval-process-through-trigger
